export enum IconKey {
  MessageCircle = 'messageCircle',
  TrendingUp = 'trendingUp',
  Instagram = 'instagram',
  Linkedin = 'linkedin',
  Sparkles = 'sparkles',
  Twitter = 'twitter',
  Shield = 'shied',
  Smile = 'smile',
  Heart = 'heart',
  Users = 'users',
  Quote = 'quote',
  Pause = 'pause',
  Brain = 'brain',
  Clock = 'clock',
  Mail = 'mail',
  Moon = 'moon',
  Sun = 'sun',
}
