export enum WordGroup {
    PEOPLE_FAMILY = "peopleFamily",
    PROFESSIONS = "professions",
    ANIMALS = "animals",
    NATURE_WEATHER = "natureWeather",
    FOOD_DRINKS = "foodDrinks",
    TRANSPORT = "transport",
    HOME_FURNITURE = "homeFurniture",
    CLOTHING = "clothing",
    TIME_DATES = "timeDates",
    COLORS_SHAPES = "colorShots",
    HOBBIES_LEISURE = "hobbiesLeisure",
    EMOTIONS_FEELINGS = "emotionsFeelings",
    HEALTH_BODY = "healthBody",
    EDUCATION_LEARNING = "educationLearning",
    TECHNOLOGY_INTERNET = "technologyInternet",
    MONEY_SHOPPING = "moneyShopping",
    PLACES_TRAVEL = "placesTravel",
    ACTIONS_MOVEMENTS = "actionsMovements",
    ABSTRACT_CONCEPTS = "abstractsConcepts",
    PARTS_OF_SPEECH = "partsOfSpeech",
}